spring:
  datasource:
    url: jdbc:mysql://39.97.123.56:3306/boss_pratical_training
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
server:
  port: 80
  #解决post请求中文乱码
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true




